server:
  servlet:
    session:
      tracking-modes: cookie #URL에 JSESSIONID가 붙어서 나가는 설정을 해제

spring:
  datasource:
    # h2 db 설정
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver

  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql

#    mysql 설정
#    url: jdbc:mysql://localhost:3306/bit_shop
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.hunbk.shop.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      hunbk:
        shop:
          repository:
            mybatis: trace
